// assets
import {
  FaPhone,
  FaMobileScreen,
  FaCommentSms,
  FaEnvelope,
  FaAddressBook,
  FaClockRotateLeft,
  FaCalendarDays,
  FaMobileScreenButton,
  FaMessage,
  FaWhatsapp,
  FaSkype,
  FaComments,
  FaImage,
  FaVideo,
  FaMapLocationDot,
  FaTableCells,
  FaSignalMessenger,
  FaWifi,
  FaExpand,
  FaClock,
  FaKeyboard,
  FaSliders,
  FaFacebook,
  FaMicrophone,
  FaFolderOpen,
  FaSnapchat,
  FaHeartPulse,
  FaLinkedin,
  FaCloudArrowUp,
} from "react-icons/fa6";
import { RiWhatsappFill } from "react-icons/ri";
// constant
const icons = {
  FaPhone,
  FaMobileScreen,
  FaCommentSms,
  FaEnvelope,
  FaAddressBook,
  FaClockRotateLeft,
  FaCalendarDays,
  FaMobileScreenButton,
  FaMessage,
  FaWhatsapp,
  FaSkype,
  FaComments,
  FaImage,
  FaVideo,
  FaMapLocationDot,
  FaTableCells,
  FaSignalMessenger,
  FaWifi,
  FaExpand,
  FaClock,
  FaKeyboard,
  FaSliders,
  FaFacebook,
  FaMicrophone,
  FaFolderOpen,
  FaSnapchat,
  FaHeartPulse,
  FaLinkedin,
  FaCloudArrowUp,
  RiWhatsappFill,
};

// ==============================|| UTILITIES MENU ITEMS ||============================== //

const utilities = {
  id: "utilities",
  title: "",
  type: "group",
  children: [
    {
      id: "device-info",
      title: "Device Information",
      type: "item",
      url: "/user/device-info",
      icon: icons.FaMobileScreen,
      breadcrumbs: false,
    },
    {
      id: "phone-logs",
      title: "Phone",
      type: "collapse",
      icon: icons.FaMobileScreenButton,
      children: [
        {
          id: "call-logs",
          title: "Call",
          type: "item",
          icon: icons.FaPhone,
          url: "/user/call-logs",
          breadcrumbs: false,
        },
        {
          id: "sms-logs",
          title: "SMS",
          type: "item",
          url: "/user/sms-logs",
          icon: icons.FaCommentSms,
          breadcrumbs: false,
        },
        {
          id: "gmail-logs",
          title: "Gmail",
          type: "item",
          url: "/user/gmail",
          icon: icons.FaEnvelope,
          breadcrumbs: false,
        },
        {
          id: "contacts-logs",
          title: "Contacts",
          type: "item", 
          url: "/user/contacts",
          icon: icons.FaAddressBook,
          breadcrumbs: false,
        },
        {
          id: "internet-history-logs",
          title: "Internet History",
          type: "item",
          url: "/user/internet-history",
          icon: icons.FaClockRotateLeft,
          breadcrumbs: false,
        },
        {
          id: "calendar-logs",
          title: "Calendar",
          type: "item",
          url: "/user/calendar",
          icon: icons.FaCalendarDays,
          breadcrumbs: false,
        },
        {
          id: "apple-health",
          title: "Apple Health",
          type: "item",
          url: "/user/apple-health",
          icon: icons.FaHeartPulse,
          breadcrumbs: false,
        },
      ],
    },
    {
      id: "messaging-logs",
      title: "Messenger",
      type: "collapse",
      icon: icons.FaMessage,
      children: [
        {
          id: "whatsapp-logs",
          title: "Whatsapp",
          type: "item",
          url: "/user/whatsapp",
          breadcrumbs: false,
          icon: icons.RiWhatsappFill,
        },
        // {
        //   id: "snapchat-logs",
        //   title: "Snapchat",
        //   type: "item",
        //   url: "/user/snapchat",
        //   breadcrumbs: false,
        //   icon: icons.FaSnapchat,
        // },
        {
          id: "signal-logs",
          title: "Signal",
          type: "item",
          url: "/user/signal",
          breadcrumbs: false,
          icon: icons.FaSignalMessenger,
        },
        // {
        //   id: "skype-logs",
        //   title: "Skype",
        //   type: "item",
        //   url: "/user/skype",
        //   icon: icons.FaSkype,
        //   breadcrumbs: false,
        // },
        // {
        //   id: "kik-logs",
        //   title: "KiK",
        //   type: "item",
        //   url: "/user/kik",
        //   icon: icons.FaComments,
        //   breadcrumbs: false,
        // },
        // {
        //   id: "line-logs",
        //   title: "Line",
        //   type: "item",
        //   icon: icons.FaComments,
        //   url: "/user/line",
        //   breadcrumbs: false,
        // },
        // {
        //   id: "viber-logs",
        //   title: "Viber",
        //   type: "item",
        //   icon: icons.FaComments,
        //   url: "/user/viber",
        //   breadcrumbs: false,
        // },
        // {
        //   id: "linkedin-logs",
        //   title: "LinkedIn",
        //   type: "item",
        //   url: "/user/linkedin",
        //   icon: icons.FaLinkedin,
        //   breadcrumbs: false,
        // },
      ],
    },
    // {
    //   id: "photos",
    //   title: "Photos",
    //   type: "item",
    //   url: "/user/photos",
    //   icon: icons.FaImage,
    //   breadcrumbs: false,
    // },
    // {
    //   id: "videos",
    //   title: "Videos",
    //   type: "item",
    //   url: "/user/videos",
    //   icon: icons.FaVideo,
    //   breadcrumbs: false,
    // },
    {
      id: "phonestorage",
      title: "Phone Storage",
      type: "item",
      url: "/user/phonestorage",
      icon: icons.FaFolderOpen,
      breadcrumbs: false,
    },
    // {
    //   id: "screenshots",
    //   title: "Screenshots",
    //   type: "item",
    //   url: "/user/screenshots",
    //   icon: icons.FaExpand,
    //   breadcrumbs: false,
    // },
    {
      id: "screen-time",
      title: "Screen Time",
      type: "item",
      url: "/user/screen-time",
      icon: icons.FaClock,
      breadcrumbs: false,
    },
    // {
    //   id: "key-logger",
    //   title: "Key Logger",
    //   type: "item",
    //   url: "/user/keylogger",
    //   icon: icons.FaKeyboard,
    //   breadcrumbs: false,
    // },
    {
      id: "location",
      title: "Location",
      type: "item",
      url: "/user/locations",
      icon: icons.FaMapLocationDot,
      breadcrumbs: false,
    },
    {
      id: "installed-apps",
      title: "Installed Apps",
      type: "item",
      url: "/user/installed-apps",
      icon: icons.FaTableCells,
      breadcrumbs: false,
    },
    // {
    //   id: "record-surround",
    //   title: "Record Surround",
    //   type: "item",
    //   url: "/user/record-surrond",
    //   icon: icons.FaMicrophone,
    //   breadcrumbs: false,
    // },
    // {
    //   id: "wifinetwork",
    //   title: "WiFi Network",
    //   type: "item",
    //   url: "/user/wifinetwork",
    //   icon: icons.FaWifi,
    //   breadcrumbs: false,
    // },
    {
      id: "manage-uploads",
      title: "Manage Uploads",
      type: "item",
      url: "/user/manage-schedule-uploads",
      icon: icons.FaCloudArrowUp,
      breadcrumbs: false,
    },
    // {
    //   id: "remotecontrol",
    //   title: "Remote Control",
    //   type: "item",
    //   url: "/user/remote-control",
    //   icon: icons.FaSliders,
    //   breadcrumbs: false,
    // },
  ],
};

export default utilities;
